### ISSUE TITLE
Column quoting problem in mysql

### ISSUE THREAD

**Issue by petersmp** [WinVector/SQLScrewdriver#2]
I just started playing with this, and I am really liking the tool (just bought Practical Data Science). However, when trying to use a mysql database, the double-quotes on column names were throwing errors. It seems that mysql chose a different convention than everyone else and uses backticks instead. I was able to get it to work with mysql by changing the quote character to a backtick on line 23 of src/com/winvector/db/TableControl.java

Do you have a suggestion for an alternative work around (e.g. a way to set ansi mode or similar in mysql from the url) or an interest in adding a switch to control column name quoting based on db type (or at least ability to turn it off if the input column names don't need escaping)?

Thanks

**Comment by JohnMount** [comment]
Thanks, I'll look into that.  The best thing I can think of is to expose a user control.

**Comment by JohnMount** [comment]
I just fixed it by adding a "colquote" key to the db connection properties/xml (see DBUtil.java line 19). 

I haven't had a chance to test it on MySQL yet.  Frankly this project is getting a little rusty and there are easier generic ways to load data (such as dbWriteTable() in R: see here http://www.win-vector.com/blog/2016/02/using-postgresql-in-r/ ).

**Comment by petersmp** [comment]
Thanks Since I hit this snag, I have found several similar alternatives as well. Thoroughly enjoying the book.
